FROM node:lts

WORKDIR /app

ARG PORT=3000

# ติดตั้ง Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

# ติดตั้ง Python และ build-essential
RUN apt update && apt install -y python3 python3-pip build-essential

COPY package.json .
COPY bun.lock .
COPY drizzle.config.ts .
COPY src src
COPY tsconfig.json .

# ใช้ Bun เพื่อจัดการ dependencies ทั่วไป
RUN bun install

# ติดตั้ง better-sqlite3 โดยใช้ npm สำหรับการคอมไพล์
RUN npm install better-sqlite3

RUN bun drizzle-kit push
RUN bun install --production

ENV PORT=${PORT}
ENV NODE_ENV production

EXPOSE ${PORT}

CMD ["bun", "src/index.ts"]
