FROM oven/bun

WORKDIR /app

# กำหนด ARG ที่สามารถรับค่าจากภายนอกตอน build
ARG PORT=3000

COPY package.json .
COPY bun.lockb .
COPY drizzle.config.ts .
COPY src src
COPY tsconfig.json .

RUN bun install

RUN bun drizzle-kit push

RUN bun install --production

# กำหนดค่า ENV จาก ARG
ENV PORT=${PORT}
ENV NODE_ENV production

# ใช้ค่า PORT ใน EXPOSE
EXPOSE ${PORT}

# ส่งค่า port ให้แอปพลิเคชัน
CMD ["bun", "src/index.ts"]